### ISSUE TITLE
Package needs a new name

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/qra#14]
Turns out there is https://cran.r-project.org/web/packages/qra/index.html

How about `qrensemble`?

**Comment by sbfnk** [comment]
Should probably do this today to avoid issues at the workshop tomorrow to avoid people installing (or having installed) the CRAN package.

**Comment by seabbs** [comment]
agree - do we want to try and have any name linkage between this and `stackr`?

**Comment by sbfnk** [comment]
I was wondering about this, also in the light of the terminology I used in https://nfidd.github.io/nfidd/sessions/forecast-ensembles.html  (e.g. `stackr` could become `mixensemble`) - one way or the other this would be good to match.

But there's also a larger conversation to be had about whether this should be just one package (which we currently promise in the README) where using a mixture or quantile average is something the use chooses from a single entry point.
